package br.com.meli.apisocialmeli.model;

public enum ProductType {
    FASHION_ACCESSORIES,
    ELECTRONICS_COMPUTERS,
    HOME_FURNITURE_DECOR,
    APPLIANCES,
    BEAUTY_PERSONAL_CARE,
    GROCERY_BEVERAGES,
    HEALTH_WELLNESS,
    SPORTS_OUTDOORS,
    TOYS_BABY_KIDS,
    PET_SUPPLIES,
    AUTOMOTIVE,
    TOOLS_HOME_IMPROVEMENT,
    OFFICE_SCHOOL_SUPPLIES,
    VIDEO_GAMES,
    BOOKS_MUSIC_MOVIES,
    OTHER
}
