spring.application.name=api-social-meli

spring.datasource.url=jdbc:mysql://localhost:3306/db-api-social-meli?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=204pipoca204
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true